name: UselessClan
version: 0.4
main: io.github.lofrol.UselessClan.UselessClan
api-version: 1.19
softdepend: [ PlaceholderAPI ]
depend: [ Vault ]
authors: [ LoFRoL ]
description: Paper plugin about simple balanced clans 
