name: UselessClan
version: 1.1
main: io.github.lofrol.UselessClan.UselessClan
api-version: 1.19
softdepend: [ Vault ]
depend: [ WorldGuard, WorldEdit, PlaceholderAPI ]
authors: [ LoFRoL ]
description: Paper plugin about simple balanced clans 
