name: UselessClan
version: 1.0
main: io.github.lofrol.UselessClan.UselessClan
api-version: 1.19
softdepend: [  ]
depend: [ Vault, WorldGuard, WorldEdit, PlaceholderAPI ]
authors: [ LoFRoL ]
description: Paper plugin about simple balanced clans 
