name: UselessClan
version: 0.8a
main: io.github.lofrol.UselessClan.UselessClan
api-version: 1.19
softdepend: [ PlaceholderAPI ]
depend: [ Vault, WorldGuard, WorldEdit ]
authors: [ LoFRoL ]
description: Paper plugin about simple balanced clans 
