name: UselessClan
version: 1.1.1-SNAPSHOT
main: io.github.lofrol.UselessClan.UselessClan
api-version: 1.20
softdepend: [ Vault ]
depend: [ WorldGuard, PlaceholderAPI ]
authors: [ 778b ]
description: Paper plugin about simple balanced clans 
